---
- name: TEST with LOCALHOST
  hosts: localhost
  gather_facts: no

  tasks:
    - name: LOCALHOST >> python_facts
      python_requirements_facts: 

- name: TEST with CONNECTION LOCAL
  hosts: us
  gather_facts: no

  tasks:
    - name: CONNECTION LOCAL >> python_facts
      python_requirements_facts: 