- name: Create US Network
  hosts: us
  gather_facts: no
  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key_id }}"
  tasks:
    - block:
        - name: Create New VPC
          ec2_vpc_net:
            cidr_block: "{{ vpc_cidr }}"
            region: "{{ aws_region }}"
            name: "{{ vpc_name }}"
            state: present
            tags: "{{ vpc_tags }}"
          tags: [vpc]
          register: create_vpc

        - name: "set fact: VPC ID"
          set_fact:
            vpc_id: "{{ create_vpc.vpc.id }}"

        - name: create VPC subnets
          ec2_vpc_subnet:
            region: "{{ aws_region }}"
            vpc_id: "{{ vpc_id }}"
            cidr: "{{ item.value.cidr }}"
            az: "{{ item.value.az }}"
            tags: "{{item.value.tags | combine({ 'Name': item.key })}}"
          with_dict: "{{ vpc_subnets }}"
          register: create_vpc_subnets


        - name: Get VPC Subnets IDs
          set_fact:
            vpc_subnet_ids: "{{ vpc_subnet_ids | default({}) | combine({ item.subnet.tags.Name: item.subnet.id }) }}"
          with_items: "{{ create_vpc_subnets.results }}"

        - debug: var=vpc_subnet_ids

        - name: Create IGW
          ec2_vpc_igw:
            region: "{{ aws_region }}"
            vpc_id: "{{ vpc_id }}" 
            state: present
            tags: "{{ vpc_tags | combine({'Name': igw_name}) }}"
          tags:
            - igw
      #delegate_to: localhost
