- name: Create US Network
  hosts: us
  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key_id }}"
  tasks:
    - block:
        - name: Create New VPC
          ec2_vpc_net:
            cidr_block: "{{ vpc_cidr }}"
            region: "{{ aws_region }}"
            name: "{{ vpc_name }}"
            state: present
            tags: "{{ vpc_tags }}"
          tags: [vpc]
          register: create_vpc
          #delegate_to: localhost

        - debug: var=create_vpc

        - name: "set fact: VPC ID"
          set_fact:
            vpc_id: "{{ create_vpc.vpc.id }}"
        
        - name: Create Subnet tags
          set_fact: 
            vpc_subnets: "{{ item.value | combine({'tags': {}})}}"
          with_dict: "{{ vpc_subnets }}"
          tags: subnet_tags
        - debug: var=vpc_subnets
          tags: subnet_tags

        - debug: var=vpc_id
        - name: create VPC subnets
          ec2_vpc_subnet:
            region: "{{ aws_region }}"
            vpc_id: "{{ vpc_id }}"
            cidr: "{{ item.value.cidr }}"
            az: "{{ item.value.az }}"
            tags:
              Name: "{{ item.key }}"
          with_dict: "{{ vpc_subnets }}"
          register: create_vpc_subnets

        - debug: var=create_vpc_subnets

        - name: Get VPC Subnets IDs
          set_fact:
            vpc_subnet_ids: "{{ vpc_subnet_ids | default({}) | combine({ item.subnet.tags.Name: item.subnet.id }) }}"
          with_items: "{{ create_vpc_subnets.results }}"

        - debug: var=vpc_subnet_ids
      delegate_to: localhost