---
- name: Get All Availability Zones
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: aws_vars.yml
  tasks:
    # - aws_az_facts:
    #     aws_access_key: AKIA55AHJ66FWSZLBF4F
    #     aws_secret_key: 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
    #     region: "{{ item }}"      
    #   with_items: "{{ all_aws_regions[6:] }}"
    #   register: az_facts
    - name: Get all VPC Facts
      ec2_vpc_net_facts:
        # aws_access_key: AKIA55AHJ66FWSZLBF4F
        # aws_secret_key: 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
        region: ap-southeast-1
      register: all_vpcs
    - debug: var=all_vpcs